### ISSUE TITLE
HI, When will the code be released? Thank you!

### ISSUE THREAD

**Issue by sev777** [zjunlp/Kformer#1]
HI, When will the code be released? Thank you!

**Comment by zxlzr** [comment]
In a few days buddy, you can leave an email and I will send you a zip file.

**Comment by xue-xue6** [comment]
Can you send me a code? Thank you.15511608518@163.com

**Comment by zxlzr** [comment]
> Can you send me a code? Thank [you.15511608518@163.com](mailto:you.15511608518@163.com)

I have sent the code, and we will release an optimized version in a few days.

**Comment by xue-xue6** [comment]
Thank you very much. I'll keep an eye on it
