### ISSUE TITLE
Why the code seems different from the idea of the paper?

### ISSUE THREAD

**Issue by CarlosGolvano** [zjunlp/Kformer#2]
I am a master's student and doing my master's thesis about your work of Kformer. I read the paper and code, and there are some relevant differences between them. At first, I expected to find a similar operation to Roberta's original FFNs where the input first goes through the key network and then through the value network. However, in your code, this happens differently. Given the two new FFNs dedicated to knowledge processing (also key-value), the input goes through both at the same time and is then combined afterwards.

My question is why you have decided to implement it that way and how it is related to what was originally stated in the paper.

P.S.: I have made a graph of Kformer according to the code itself as I see it.

![Kformer_esquema](https://user-images.githubusercontent.com/47215458/174999559-ece7df7c-71e0-4b46-998c-506b4e938ed8.png)

**Comment by littlefive5** [comment]
Thanks for your question. 
It is actually a problem of Partitioned Matrix Computing. 
There is a video about the computation of Partitioned Matrix. https://www.youtube.com/watch?v=5MFWywYY9bE
Based on the theory above, I make a simple prove here:
![prove](https://user-images.githubusercontent.com/36941249/175017199-e95ab0c1-70bd-4acb-b7eb-dfd8979b27da.jpg)
You can find that concatenating the knowledge vector at the end of the matrix is equal to our implementation. 
Hope this may help you. 
Let me know if you have other questions!

**Comment by CarlosGolvano** [comment]
Thank you for the explanation. 
I had been trying to understand it for days but now I can finally get it.
